// SecurityArts page build — precompiles each Design System app page's JSX and
// removes the runtime unpkg/Babel dependency that caused black screens.
//
// What it does, per app page under "SecurityArts Design System/website/ui_kits":
//   1. One-time extraction: the inline <script type="text/babel"> block is moved
//      to a sibling <page>.jsx file — the editable SOURCE from then on.
//   2. Compile: <page>.jsx → <page>.app.js with esbuild (JSX → React.createElement,
//      target es2019). No bundling — pages keep using the global React/DS bundle.
//   3. Rewrite HTML:
//        unpkg react/react-dom (dev)  → local vendored production UMDs
//        @babel/standalone            → removed
//        inline text/babel block      → <script src="<page>.app.js" defer>
//        + assets/failsafe.js         → black-screen watchdog (see that file)
//
// Idempotent: re-runs recompile .jsx → .app.js and leave HTML untouched.
//   node scripts/build-pages.mjs           build
//   node scripts/build-pages.mjs --check   build to temp + fail if outputs drift (CI)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transformSync } from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = path.join(ROOT, "SecurityArts Design System", "website");
const KITS = path.join(SITE, "ui_kits");
const VENDOR_REL = "../../assets/vendor"; // every app page sits two levels under website/

const CHECK = process.argv.includes("--check");
let drift = 0;

const PAGES = [];
for (const kit of fs.readdirSync(KITS)) {
  const dir = path.join(KITS, kit);
  if (!fs.statSync(dir).isDirectory()) continue;
  for (const f of fs.readdirSync(dir)) if (f.endsWith(".html")) PAGES.push(path.join(dir, f));
}

const BABEL_TAG = /<script[^>]*@babel\/standalone[^>]*><\/script>\s*\n?/;
const REACT_TAG = /<script[^>]*unpkg\.com\/react@[^>]*><\/script>/;
const REACT_DOM_TAG = /<script[^>]*unpkg\.com\/react-dom@[^>]*><\/script>/;
const INLINE_BLOCK = /<script type="text\/babel">([\s\S]*?)<\/script>/;

function compile(jsxSource, label) {
  const out = transformSync(jsxSource, {
    loader: "jsx",
    jsx: "transform", // classic runtime → React.createElement against the global React
    target: "es2019",
    sourcefile: label,
  });
  return "// Generated by scripts/build-pages.mjs — edit the sibling .jsx, not this file.\n" + out.code;
}

function writeIfChanged(file, content) {
  const prev = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (prev === content) return false;
  if (CHECK) { console.error(`DRIFT: ${path.relative(ROOT, file)} is stale — run \`npm run build\``); drift++; return false; }
  fs.writeFileSync(file, content);
  return true;
}

let converted = 0, compiled = 0, untouched = 0;
for (const htmlPath of PAGES) {
  const base = path.basename(htmlPath, ".html");
  const dir = path.dirname(htmlPath);
  const jsxPath = path.join(dir, base + ".jsx");
  const appJsPath = path.join(dir, base + ".app.js");
  const appJsRel = base + ".app.js";
  let html = fs.readFileSync(htmlPath, "utf8");

  const inline = html.match(INLINE_BLOCK);
  if (inline) {
    // one-time conversion: extract source, rewrite the HTML
    if (CHECK) { console.error(`DRIFT: ${path.relative(ROOT, htmlPath)} still has a text/babel block`); drift++; continue; }
    fs.writeFileSync(jsxPath, inline[1].replace(/^\n/, ""));
    html = html
      .replace(REACT_TAG, `<script src="${VENDOR_REL}/react.production.min.js"></script>`)
      .replace(REACT_DOM_TAG, `<script src="${VENDOR_REL}/react-dom.production.min.js"></script>`)
      .replace(BABEL_TAG, "")
      .replace(INLINE_BLOCK, `<script src="${appJsRel}" defer></script>`);
    // watchdog goes right before the app script so it observes the mount
    if (!html.includes("assets/failsafe.js")) {
      html = html.replace(`<script src="${appJsRel}" defer></script>`,
        `<script src="../../assets/failsafe.js"></script>\n<script src="${appJsRel}" defer></script>`);
    }
    fs.writeFileSync(htmlPath, html);
    converted++;
  } else if (!fs.existsSync(jsxPath)) {
    untouched++; // static page (no app code) — nothing to do
    continue;
  }

  const out = compile(fs.readFileSync(jsxPath, "utf8"), path.relative(ROOT, jsxPath));
  if (writeIfChanged(appJsPath, out)) compiled++;

  // sanity: the compiled file must parse as plain JS
  try { new Function(fs.readFileSync(appJsPath, "utf8")); } catch (e) {
    console.error(`COMPILE PRODUCED INVALID JS for ${appJsPath}: ${e.message}`); process.exit(1);
  }
}

// vendor files must exist for the pages to boot
for (const v of ["react.production.min.js", "react-dom.production.min.js"]) {
  const p = path.join(SITE, "assets", "vendor", v);
  if (!fs.existsSync(p)) { console.error(`MISSING VENDOR FILE: ${path.relative(ROOT, p)} — see scripts/README`); process.exit(1); }
}

if (CHECK && drift) { console.error(`${drift} stale artifact(s).`); process.exit(1); }
console.log(`build-pages: ${PAGES.length} pages scanned · ${converted} converted · ${compiled} recompiled · ok`);
